import type { Metadata } from "next";
import { Bricolage_Grotesque, Geist, Geist_Mono } from "next/font/google";
import ScrollRigRoot from "./components/scroll-rig/ScrollRigRoot";
import KroenShell from "./components/kroen/KroenShell";
import "./globals.css";
import "./styles/kroen-experience.css";

const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: "variable",
  axes: ["wdth", "opsz"],
  variable: "--font-bricolage",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolageGrotesque.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollRigRoot />
        <KroenShell>{children}</KroenShell>
      </body>
    </html>
  );
}
